# Generated by Django 6.0.3 on 2026-03-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                (
                    "price_per_night",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
                ),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
