# Generated by Django 6.0.3 on 2026-03-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_assigned_to_room_isavailable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="room",
            name="isAvailable",
        ),
    ]
