# Generated by Django 6.0.3 on 2026-03-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_remove_room_assigned_to_remove_room_isavailable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="number",
            new_name="room_number",
        ),
    ]
